version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# This part is necessary otherwise the project is not built
# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .

# By default readthedocs does not checkout git submodules
submodules:
  include: all
