defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "corinfomax-imagenet100" # change here for cifar100
method: "corinfomax"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  R_ini: 1.0          # coefficient of initial covariance
  la_R: 1e-2         # forgetting factor for covariance
  la_mu: 1e-2        # forgetting factor for mean
  R_eps_weight: 1e-6 # diagonal perturbation factor of covariance matrix R1
  alpha_tradeoff: 500 # tradeoff coefficient for invariance loss

data:
  dataset: imagenet100
  train_path: "./datasets/imagenet100/train"
  val_path: "./datasets/imagenet100/val"
  format: "dali"
  num_workers: 8
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.5
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed