defaults:
  - _self_
  - augmentations: empssl.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "empssl-cifar" # change here for cifar100
pretrain_method: "empssl"
pretrained_feature_extractor: "/home/AD/ofsk222/Research/clones/solo-learn/trained_models/empssl/l3tmegmp/empssl-cifar10-l3tmegmp-ep=0.ckpt"

backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 512
  num_crops_val: 20

data:
  dataset: cifar10 # change here for cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 16
optimizer:
  name: "adam"
  batch_size: 768
  lr: 0.001
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [40, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
