defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "sear-cifar100-linear-output512" # change here for cifar100
pretrain_method: "sear"
pretrained_feature_extractor: "/home/AD/ofsk222/Research/clones/solo-learn/trained_models/sear_projection_sweep/proj_output_512/sear-cifar100-aayy6e6x-ep=999.ckpt"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 512
  alpha: 2
  kernel_type: "linear"

data:
  dataset: cifar100 # change here for cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.001
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [40, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 100
devices: [1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
