defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-stl10-linear"
pretrained_feature_extractor: "/home/AD/ofsk222/Research/clones/solo-learn/trained_models/stl10_models/byol-stl10-74su6fg3-ep=499.ckpt"
backbone:
  name: "resnet18"
pretrain_method: "byol"
data:
  dataset: stl10
  train_path: "./datasets/stl10"
  val_path: "./datasets/stl10"
  format: "image_folder"
  num_workers: 8
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
