defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "corinfomax-cifar100" # change here for cifar100
method: "corinfomax"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  R_ini: 1.0          # coefficient of initial covariance
  la_R: 1e-2         # forgetting factor for covariance
  la_mu: 1e-2        # forgetting factor for mean
  R_eps_weight: 1e-6 # diagonal perturbation factor of covariance matrix R1
  alpha_tradeoff: 1000 # tradeoff coefficient for invariance loss

data:
  dataset: cifar100 # change here for cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
