defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "frossl-imagenet100-linear"
pretrained_feature_extractor: None
backbone:
  name: "resnet18"
pretrain_method: "frossl"
data:
  dataset: imagenet100
  train_path: "./datasets/imagenet100/train"
  val_path: "./datasets/imagenet100/val"
  format: "dali"
  num_workers: 16
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
